name: Azure App Service - homebrewery-images Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    
    - run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: homebrewery-images
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0F5979D140B74F86B73FA07F5FFD48A2 }}
        package: ${{ github.workspace }}/build/libs/*.jar

